import React from 'react';

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-blue-600 text-white">
        <div className="max-w-3xl mx-auto px-6 py-12 text-center">
          <h1 className="text-3xl font-bold mb-2">Disclaimer</h1>
          <p className="text-blue-100">Last updated: December 9, 2025</p>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-7xl mx-auto px-6 py-12">
        
        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">General Information</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            The information provided by KodeCompiler on our website and through our online coding platform is for general informational and educational purposes only. All information on the site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the site or through our services.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the site or reliance on any information provided on the site. Your use of the site and your reliance on any information on the site is solely at your own risk.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">No Professional Advice</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            The information provided through KodeCompiler is not intended to be a substitute for professional advice, including but not limited to professional programming advice, software development consultation, legal advice, or technical support from qualified professionals.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            While we strive to provide helpful coding tools and resources, we do not claim to provide professional software development services or expert consultation. Always seek the advice of qualified professionals with any questions you may have regarding software development, security practices, or deployment of code in production environments.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Never disregard professional advice or delay in seeking it because of something you have read or learned on our platform. The code examples, tutorials, and documentation provided are for educational purposes and may not be suitable for production use without proper review and testing.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Code Execution and Results</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            KodeCompiler provides an online platform for compiling and executing code in various programming languages. We make no warranties or guarantees about the accuracy, reliability, or correctness of code execution results. The output generated by our platform is provided "as is" without any warranty of any kind.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            You are solely responsible for reviewing, testing, and validating any code you write or execute on our platform. We are not responsible for any errors, bugs, security vulnerabilities, or unintended behavior in your code. Code that executes successfully on our platform may behave differently in other environments.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Our platform executes code in isolated containers with specific resource limitations and security constraints. These limitations may affect how your code runs and may not reflect the behavior of the same code in other environments. Always thoroughly test your code in appropriate environments before deploying it for production use.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Educational Content</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Any educational content, tutorials, code examples, or documentation provided on KodeCompiler is intended for learning purposes only. While we strive to ensure accuracy, we cannot guarantee that all content is up-to-date, complete, or error-free.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            Programming languages, frameworks, libraries, and best practices evolve rapidly. Information that was accurate at the time of publication may become outdated. We recommend consulting official documentation and current resources when making important development decisions.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Code examples provided are simplified for educational purposes and may not include all error handling, security measures, or best practices required for production applications. Always adapt examples to meet your specific requirements and security standards.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">External Links Disclaimer</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Our website and platform may contain links to external websites or resources that are not provided or maintained by KodeCompiler. These links are provided for your convenience and informational purposes only.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            We have no control over the nature, content, or availability of external sites. The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them. We are not responsible for the content, accuracy, or opinions expressed on external websites.
          </p>
          <p className="text-gray-700 leading-relaxed">
            If you access external links, you do so at your own risk. We are not liable for any loss or damage arising from your use of external websites or resources.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Service Availability</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            While we strive to maintain high availability and performance, we do not guarantee that our services will be available at all times or that they will be uninterrupted, secure, or error-free. Our platform may experience downtime due to maintenance, technical issues, or circumstances beyond our control.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            We reserve the right to modify, suspend, or discontinue any aspect of our services at any time without prior notice. We may also impose limits on certain features or restrict access to parts or all of the services without notice or liability.
          </p>
          <p className="text-gray-700 leading-relaxed">
            We are not responsible for any loss of data, code, or work product that may occur due to service interruptions, technical failures, or other issues. We strongly recommend that you maintain backups of any important code or data.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Security Disclaimer</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            While we implement reasonable security measures to protect our platform and user data, no method of transmission over the internet or electronic storage is completely secure. We cannot guarantee the absolute security of any information transmitted to or stored on our platform.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            You are responsible for maintaining the security of your account credentials and for all activities that occur under your account. Do not share your password with others or use the same password across multiple services.
          </p>
          <p className="text-gray-700 leading-relaxed">
            If you discover any security vulnerabilities or concerns with our platform, please report them to us immediately. Do not exploit security issues or access data that does not belong to you.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Third-Party Services and Integrations</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            KodeCompiler may integrate with or provide access to third-party services, libraries, frameworks, or APIs. We are not responsible for the functionality, availability, accuracy, or security of third-party services.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            Your use of third-party services is subject to their respective terms of service and privacy policies. We make no representations or warranties regarding third-party services and are not liable for any issues arising from your use of such services.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Third-party libraries, packages, or dependencies used in code examples or available through our platform may have their own licenses, terms, and conditions. You are responsible for complying with all applicable licenses when using third-party code or libraries.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Limitation of Liability</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            To the fullest extent permitted by law, KodeCompiler, its affiliates, officers, employees, agents, partners, and licensors shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of our services or inability to use our services.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            This includes but is not limited to damages for loss of profits, data, business opportunities, goodwill, or other intangible losses, even if we have been advised of the possibility of such damages.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Some jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages. In such jurisdictions, our liability shall be limited to the maximum extent permitted by law.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">User Responsibility</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            You acknowledge that you are solely responsible for your use of KodeCompiler and any code you write, compile, or execute on our platform. You are responsible for ensuring that your use of our services complies with all applicable laws, regulations, and third-party agreements.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            You are responsible for implementing appropriate security measures, error handling, testing, and validation for any code you develop. Do not rely solely on our platform for critical applications without proper testing and backup procedures.
          </p>
          <p className="text-gray-700 leading-relaxed">
            By using our platform, you accept all risks associated with online code compilation and execution, including but not limited to data loss, security vulnerabilities, and unexpected behavior.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to This Disclaimer</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            We reserve the right to modify this Disclaimer at any time. Changes will be effective immediately upon posting to our website. We will update the "Last updated" date at the top of this page when changes are made.
          </p>
          <p className="text-gray-700 leading-relaxed">
            Your continued use of our services following the posting of changes constitutes your acceptance of such changes. We encourage you to review this Disclaimer periodically to stay informed of any updates.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Information</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            If you have any questions or concerns about this Disclaimer or need clarification on any of the terms, please contact us. We are here to help and will respond to your inquiries as promptly as possible.
          </p>
          <p className="text-gray-700 leading-relaxed mb-2">
            You can reach us at:
          </p>
          <p className="text-gray-700 leading-relaxed mb-1">
            Email: <a href="mailto:legal@kodecompiler.com" className="text-blue-600 hover:underline">legal@kodecompiler.com</a>
          </p>
          <p className="text-gray-700 leading-relaxed">
            Support: <a href="mailto:support@kodecompiler.com" className="text-blue-600 hover:underline">support@kodecompiler.com</a>
          </p>
        </section>

      </main>
    </div>
  );
};

export default Disclaimer;